spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentdb
    username: payment
    password: payment

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

  rabbitmq:
    host: localhost
    port: 5672

server:
  port: 7070