spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentdb
    username: payment
    password: payment

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

payment:
  messaging:
    exchange: payment.exchange
    fraud.queue: payment.fraud.queue
    notification.queue: payment.notification.queue
    routing-key: MoneyTransferred

server:
  port: 7070
